
class columnNames:
    RECORDED_TIME = 'RecordedAtTime'
    PUBLISHED_LINE = 'PublishedLineName'
    DIRECTION_REF = 'DirectionRef'
    ORIGIN_NAME = 'OriginName'
    ORIGIN_LAT = 'OriginLat'
    ORIGIN_LONG = 'OriginLong'
    DESTINATION_NAME = 'DestinationName'
    DESTINATION_LAT = 'DestinationLat'
    DESTINATION_LONG = 'DestinationLong'
    VEHICLE_REF = 'VehicleRef'
    VEHICLE_LAT = 'VehicleLocation.Latitude'
    VEHICLE_LONG = 'VehicleLocation.Longitude'
    NEXT_STOP_POINT_NAME = 'NextStopPointName'
    ARRIVAL_PROXIMITY_TEXT = 'ArrivalProximityText'
    DISTANCE_FROM_STOP = 'DistanceFromStop'
    EXPECTED_ARRIVAL = 'ExpectedArrivalTime'
    SCHEDULED_ARRIVAL = 'ScheduledArrivalTime'